name: setup-git-credentials
description: Allow cloning private repositories
author: Fusion Engineering
inputs:
  credentials:
    description: git credentials use

runs:
  using: node12
  main: lib/main.js
