name: setup-git-credentials
description: Allow cloning private repositories
author: Fusion Engineering
icon: unlock
color: orange
inputs:
  secret:
    description: secret containing the git credentials
    default: GIT_CREDENTIALS

runs:
  using: node12
  main: lib/main.js
